### ISSUE TITLE
Accept period "." in environment variable names

### ISSUE THREAD

**Issue by JamesJJ** [schmichael/go-envparse#1]
Currently https://github.com/hashicorp/go-envparse/blob/master/envparse.go#L135 limits ENV variable names to [A-Za-z_] . I understand this follows various standards for environment variable names, and agree it is a sensible default.

I am trying to migrate [100 +] components to NOMAD, and load env variables from consul using `template {` with `env = true`.  My problem is that, unfortunately, the standards for env key names were not followed so rigidly when these components were developed. There are many key names following HOCON key or java options naming  i.e. the key names contain a dot `.`   For example:

```
catalog.host = "host.example.com"
catalog.port = "443"
networkaddress.cache.ttl = "60"
```
... and so on.

==> Would is be possible to allow dot  `.`   in env key names in the `env = true` template stanza?

Many thanks, James.

**Comment by schmichael** [comment]
Fixed in #2
